table Orders
	lineageTag: fa144fef-0041-4ccd-8eff-dc7ff7635c4b

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: d4998da8-e5b7-4c59-b100-84ef3cd95b08
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order Priority'
		dataType: string
		lineageTag: c26a7a2b-cbb3-4889-b01c-fe1ac9c681b6
		summarizeBy: none
		sourceColumn: Order Priority

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: a9bbf835-ed6b-4c85-a271-beb4b24d0ca5
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Price'
		dataType: double
		lineageTag: 75f2b588-9d00-4f70-b765-c62671d26e6c
		summarizeBy: sum
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Shipping Cost'
		dataType: double
		lineageTag: 974d487f-05fa-4894-89bc-f38d3508b9a0
		summarizeBy: sum
		sourceColumn: Shipping Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Customer ID'
		dataType: int64
		formatString: 0
		lineageTag: e73ea51f-85ed-4f3d-85ff-1f348f6db21d
		summarizeBy: count
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: db7f66e7-2992-4745-b1e0-c21f8e912f2f
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: a153ae46-1057-46a2-97e2-05af292cd83e
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment'
		dataType: string
		lineageTag: 7d11e08b-bc9e-42ee-82d6-b5973d3ba69c
		summarizeBy: none
		sourceColumn: Customer Segment

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		lineageTag: e41d89e3-8df8-41a9-8efd-625c29d2f280
		summarizeBy: none
		sourceColumn: Product Category

		annotation SummarizationSetBy = Automatic

	column 'Product Sub-Category'
		dataType: string
		lineageTag: 556a4529-b402-433a-b536-0617d5712f44
		summarizeBy: none
		sourceColumn: Product Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Container'
		dataType: string
		lineageTag: 45d1de13-6622-49d4-aff0-cd10de6e8c53
		summarizeBy: none
		sourceColumn: Product Container

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 0389a1aa-2a00-4de6-b1ca-64ff2a0122e2
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column 'Product Base Margin'
		dataType: double
		lineageTag: 32b60206-bda7-4382-9ce9-5b9e625415fb
		summarizeBy: sum
		sourceColumn: Product Base Margin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Country
		dataType: string
		lineageTag: dbc4e9d7-067a-42dd-ba60-bae335ee040d
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 0c284bc2-6dd5-4410-9309-575cbeb9f7cd
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'State or Province'
		dataType: string
		lineageTag: 9aae0954-e51d-4e1f-b29e-8f8de15da7fa
		summarizeBy: none
		sourceColumn: State or Province

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: dba4f032-050c-426a-9426-d7215052664b
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 17427726-3087-4a6b-93d3-5c8c9140fc60
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 791021ee-ab26-4a42-9147-f4c5aa951ad0
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 28368ee7-c3f5-4aef-b642-6f38f8fb86ec
			defaultHierarchy: LocalDateTable_c059fb17-3835-480c-b3ca-84e65c196867.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 595f7db4-3b58-4b23-acac-9968603b1507
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 8a25e55b-46b0-4236-beae-df00ad064e53
			defaultHierarchy: LocalDateTable_b8e245bb-f006-4ead-8a23-fba8ff9c51af.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Profit
		dataType: double
		lineageTag: 9bf1c014-f3c0-4abc-8885-1274708aba97
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Quantity ordered new'
		dataType: int64
		formatString: 0
		lineageTag: 2874528c-3ff2-453e-91d5-c95b2208bfdc
		summarizeBy: sum
		sourceColumn: Quantity ordered new

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 081ed9b8-a7c7-4eb3-88cf-27fe2f29dac9
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order ID'
		dataType: int64
		formatString: 0
		lineageTag: 2ea64816-20a0-4e03-974c-a96393933091
		summarizeBy: count
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column Column26
		dataType: string
		lineageTag: 734e9f33-eabe-4206-9a53-03b2232776f4
		summarizeBy: none
		sourceColumn: Column26

		annotation SummarizationSetBy = Automatic

	column Column27
		dataType: string
		lineageTag: 7a4327e2-a524-4185-bef2-b1f752118d63
		summarizeBy: none
		sourceColumn: Column27

		annotation SummarizationSetBy = Automatic

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\265400\Downloads\SuperStoreUS-2015.xlsx"), null, true),
				    Orders_Sheet = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order Priority", type text}, {"Discount", type number}, {"Unit Price", type number}, {"Shipping Cost", type number}, {"Customer ID", Int64.Type}, {"Customer Name", type text}, {"Ship Mode", type text}, {"Customer Segment", type text}, {"Product Category", type text}, {"Product Sub-Category", type text}, {"Product Container", type text}, {"Product Name", type text}, {"Product Base Margin", type number}, {"Country", type text}, {"Region", type text}, {"State or Province", type text}, {"City", type text}, {"Postal Code", Int64.Type}, {"Order Date", type date}, {"Ship Date", type date}, {"Profit", type number}, {"Quantity ordered new", Int64.Type}, {"Sales", type number}, {"Order ID", Int64.Type}, {"Column26", type any}, {"Column27", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

